# Generated by Django 5.2.8 on 2025-11-09 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomizationOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('base', 'Base'), ('size', 'Size'), ('filling', 'Filling'), ('flavor', 'Flavor'), ('decor', 'Decor')], max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('extra_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('is_available', models.BooleanField(default=True)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('image', models.ImageField(upload_to='post_images/%Y/%m/%d')),
            ],
        ),
        migrations.CreateModel(
            name='ProductCustomization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(blank=True, max_length=200, null=True)),
                ('total_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('base', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='base_customizations', to='bakery_app.customizationoption')),
                ('decor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decor_customizations', to='bakery_app.customizationoption')),
                ('filling', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filling_customizations', to='bakery_app.customizationoption')),
                ('flavor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flavor_customizations', to='bakery_app.customizationoption')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bakery_app.product')),
                ('size', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='size_customizations', to='bakery_app.customizationoption')),
            ],
        ),
    ]
