from django.urls import path,include
from rest_framework.routers import DefaultRouter
from .views import (
    ProductListView,
    CustomizationOptionListView,
    ProductCustomizationCreateView,
    CartViewSet,
    CartItemViewSet
)

# Router automatically creates URLs for ViewSets
router = DefaultRouter()
router.register(r'carts', CartViewSet, basename='cart')
router.register(r'cart-items', CartItemViewSet, basename='cartitem')

urlpatterns = [
    path('products/', ProductListView.as_view(), name='product-list'),
    path('options/', CustomizationOptionListView.as_view(),name='options'),
    path('customizations/', ProductCustomizationCreateView.as_view(), name='customization-create'),
   
    # Cart endpoints (auto-generated by router)   
    path('',include(router.urls)),
]

